name: flutest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  flutter_native_splash: ^2.2.19
  ffi:
  dio: ^5.1.2
  http: ^0.13.6
  intl:
  vector_math: ^2.1.0
  shirne_dialog:
  event_bus: ^2.0.0
  image:
  zxing_lib: 
  screenshot: ^2.0.0
  logging: ^1.0.2
  extended_nested_scroll_view:
  imageview360:
  panorama:
  flutter_svg: ^2.0.7
  my_plugin:
    path: plugins/my_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
    - assets/obj/
    - assets/images/
    - assets/svg/
